theme: jekyll-theme-slate
show_downloads: "true"
github:
  zip_url: https://github.com/Haschtl/ModernWebsocketClient/releases
  apk_url: https://drive.google.com/open?id=1uU103UpTB0V5ji9e6_McrTEqoVD_m-NM
